# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 297cd30a2b294ab7e9e8707077cb317f76ee62e04f62fa594bf67db078925f9408926fd45b9b5b60dfc6790a2485f13211f61acd9bc3bb8bd190d2a390e49721

test:
  secret_key_base: 7d635f1bdf02a6ca36db8c45671bd295b13bc81b4234438477c5e12c49e7f5c07e95650d5fb90201fe35faa10184fea06b3305a81afb3a9b4a6a6e1094571f63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
